disabled_rules: # rule identifiers turned on by default to exclude from running
  - line_length
  - force_cast
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Example/Pods
